### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by lhs-devloper** [expiator8/fastapi#2]
서버는 uvicorn 다운받아서 돌리면 되나용?

**Comment by expiator8** [comment]
저때는 gunicorn으로 테스트해서 uvicorn으로 하려면 설치하고 돌리면 될것같습니다

+
main.py에서 debug_toolbar를 실행할때 swagger가 엄청 느려지더라구요 그래서 지금은 
QUERY_DEBUG 변수를 False로 두고 쿼리 확인이 필요할때만 True로 바꾸는 식으로 따로 관리하고 있어요.

if settings.QUERY_DEBUG:
    app.add_middleware(
        DebugToolbarMiddleware,
        panels=[
            "debug_toolbar.panels.sqlalchemy.SQLAlchemyPanel",
        ],
    )

+
config setting에서
.__to_string__(hide_password=not self.DEBUG)는
.__to_string__(hide_password=False) False로 항상 바꿔놓아야 할 것 같아요.
DEBUG가 False일때만 password를 숨기고 싶었는데 hide_password=True면 db 연결 자체가 안되더라구요

**Comment by expiator8** [comment]
아
.to_string(hide_password=not self.DEBUG)
이건 다른 문제였네요 그냥 저렇게 써도 될 것 같아요 하하

**Comment by expiator8** [comment]
> 저때는 gunicorn으로 테스트해서 uvicorn으로 하려면 설치하고 돌리면 될것같습니다
> 
> 
> main.py에서 debug_toolbar를 실행할때 swagger가 엄청 느려지더라구요 그래서 지금은 QUERY_DEBUG 변수를 False로 두고 쿼리 확인이 필요할때만 True로 바꾸는 식으로 따로 관리하고 있어요.
> 
> if settings.QUERY_DEBUG: app.add_middleware( DebugToolbarMiddleware, panels=[ "debug_toolbar.panels.sqlalchemy.SQLAlchemyPanel", ], )
> 
> 
> config setting에서 .**to_string**(hide_password=not self.DEBUG)를 하니까 첨엔 잘됐는데 어느 순간?부터 에러나더라구요 .**to_string**(hide_password=False) False로 항상 바꿔놓는게 좋을 것 같아요

아
.to_string(hide_password=not self.DEBUG)
이건 다른 문제였네요 그냥 저렇게 써도 될 것 같아요 하하

**Comment by lhs-devloper** [comment]
Thanks, 감사합니당
